apiVersion: batch/v1
kind: Job
metadata:
  name: ctgnratr-job
spec:
  template:
    spec:
      containers:
      - name: ctgnratr-job
        image: yash5090/ctgnratr:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
